# .github/workflows/build-and-push.yml

name: Run Automated Tests

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install all requirements for testing
          pip install -r requirements.txt
          # Download NLTK data needed for the preprocessing test
          python -c "import nltk; nltk.download(['punkt', 'punkt_tab', 'stopwords', 'wordnet', 'averaged_perceptron_tagger', 'averaged_perceptron_tagger_eng'])"

      - name: Run tests with pytest and generate coverage report
        run: pytest --cov=.
